# Generated by Django 4.1.4 on 2023-01-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('type_transact', models.CharField(default='withdraw', editable=False, max_length=23)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('momo_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_momo_agent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_withdraw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('type_transact', models.CharField(default='transfer', editable=False, max_length=23)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('type_transact', models.CharField(default='deposit', editable=False, max_length=23)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('momo_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_agent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_receive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('type_transact', models.CharField(default='airtime', editable=False, max_length=23)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
