# Generated by Django 4.1.4 on 2023-01-08 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='momo_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_agent', to='account.agentaccount'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='momo_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_momo_agent', to='account.agentaccount'),
        ),
    ]
