# Generated by Django 4.1.4 on 2022-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='type_transact',
            field=models.CharField(default='airtime', editable=False, max_length=23),
        ),
        migrations.AddField(
            model_name='deposit',
            name='type_transact',
            field=models.CharField(default='deposit', editable=False, max_length=23),
        ),
        migrations.AddField(
            model_name='transfer',
            name='type_transact',
            field=models.CharField(default='transfer', editable=False, max_length=23),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='type_transact',
            field=models.CharField(default='withdraw', editable=False, max_length=23),
        ),
    ]
