# Generated by Django 4.1.4 on 2023-01-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mtnaccount_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='agentaccount',
            name='agent_code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
