# Generated by Django 4.1.4 on 2023-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_agentaccount_id_alter_agentaccount_agent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentaccount',
            name='agent_code',
            field=models.IntegerField(unique=True),
        ),
    ]
