# Generated by Django 4.1.4 on 2023-01-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_agentaccount_id_alter_agentaccount_agent_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='agentaccount',
            name='agent_code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
