# Generated by Django 4.1.4 on 2023-01-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_agentaccount_id_alter_agentaccount_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='momo_agent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
