# Generated by Django 4.1.4 on 2023-01-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_momo_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='momo_agent',
            field=models.BooleanField(default=False),
        ),
    ]
